project:
  type: book

book:
  title: "LLMOps Notes"
  author: "Kittipos Sirivongrungson"
  date: today
  repo-url: https://github.com/Lightbridge-KS/llmops-notes
  site-url: https://llmops-notes-lightbridge.netlify.app
  chapters:
    - index.qmd
    - part: Hardware for LLM
      chapters: 
        - text: "LLM Hardware Specification"
          href: "contents/hardware/llm-hardware-req.qmd"
        - text: "LLM Hardware Calculators"
          href: "contents/hardware/llm-hardware-calculators.qmd"

format:
  html:
    theme:
      light:
      - cosmo
      dark:
      - darkly
    toc-depth: 4

freeze: auto
